import React, { useState, useRef } from 'react';
import { Staff } from '../types';
import { chucVuToRole } from '../App';
import { downscaleImage } from '../lib/firebase';
import { X, Save, User } from 'lucide-react';
import { useModalA11y } from '../utils/useModalA11y';
import StaffDirectoryPicker, { DirectoryPerson } from './StaffDirectoryPicker';

type ChucVu = 'Ban giám đốc' | 'Trưởng phòng' | 'Phó phòng' | 'Quản lý' | 'Chuyên viên đấu thầu' | 'Quản trị hệ thống' | 'Khách (chỉ xem)';

interface StaffEditModalProps {
  member?: Staff | null; // If null/undefined, we are adding a new account
  existingStaff: Staff[];
  currentUserRole?: 'BOOD' | 'MANAGER' | 'STAFF' | 'VIEWER'; // vai trò người đang thao tác (để giới hạn quyền L2)
  onSave: (updated: Staff) => void;
  onClose: () => void;
}

export default function StaffEditModal({ member, existingStaff, currentUserRole, onSave, onClose }: StaffEditModalProps) {
  const panelRef = useModalA11y(onClose);
  const isNew = !member;
  // Level 2 (Quản lý) chỉ được tạo tài khoản Chuyên viên (Level 3) và KHÔNG được xem mật khẩu của người khác.
  const isManager = currentUserRole === 'MANAGER';

  // Auto-generate ID if it's a new account
  const autoGeneratedId = React.useMemo(() => {
    const ids = existingStaff.map(s => {
      const num = parseInt(s.id.replace('S', ''), 10);
      return isNaN(num) ? 0 : num;
    });
    const maxId = ids.length > 0 ? Math.max(...ids) : 0;
    const nextNum = maxId + 1;
    return `S${String(nextNum).padStart(3, '0')}`;
  }, [existingStaff]);

  const [customId, setCustomId] = useState(member?.id || autoGeneratedId);
  const [hoTen, setHoTen] = useState(member?.hoTen || '');
  // Nhân sự chọn từ danh bạ App Tổng (chỉ dùng khi isNew) — thay cho gõ tay Mã Nhân sự
  // + Họ và Tên (Sếp chốt 27/08/2026). id = uid App Tổng, TRÙNG khoá staff/{uid} mà
  // route SSO sẽ dùng khi chính người đó tự đăng nhập sau này — tránh tạo trùng hồ sơ.
  const [pickedPerson, setPickedPerson] = useState<DirectoryPerson | null>(null);
  const [chucVu, setChucVu] = useState<ChucVu>(
    member?.chucVu || 'Chuyên viên đấu thầu'
  );
  const [username, setUsername] = useState(member?.username || '');
  const [email, setEmail] = useState(member?.email || '');
  const [mustChangePassword, setMustChangePassword] = useState<boolean>(member?.mustChangePassword ?? isNew);
  const [role, setRole] = useState<'BOOD' | 'MANAGER' | 'STAFF' | 'VIEWER'>(
    member?.role || chucVuToRole(member?.chucVu)
  );
  // Quản lý phụ trách (đội ngũ) — chỉ Trưởng phòng (L1) được gán, chỉ áp cho nhân viên Level 3.
  const [quanLyPhuTrachId, setQuanLyPhuTrachId] = useState<string>(member?.quanLyPhuTrachId || '');
  // Danh sách Quản lý (L2) còn làm việc để chọn.
  // Người ĐANG được gán nhưng không còn là Quản lý (vừa lên Trưởng phòng, đổi quyền khác, hoặc
  // nghỉ việc) vẫn được giữ trong danh sách để select hiện ĐÚNG người đang gán, không tụt về
  // "Chưa gán" khiến Trưởng phòng tưởng dữ liệu mất (chị Trâm báo 28/07/2026 — dữ liệu vẫn còn
  // nguyên, chỉ là dropdown lọc theo role hiện tại nên không tìm thấy option khớp).
  const managerOptions = React.useMemo(() => {
    const list = existingStaff.filter(s => !s.daNghi && (s.role || chucVuToRole(s.chucVu)) === 'MANAGER');
    const dangGanId = member?.quanLyPhuTrachId;
    if (dangGanId && !list.some(s => s.id === dangGanId)) {
      const nguoiDangGan = existingStaff.find(s => s.id === dangGanId);
      if (nguoiDangGan) list.push(nguoiDangGan);
    }
    return list;
  }, [existingStaff, member?.quanLyPhuTrachId]);

  // Ảnh đại diện: mặc định trống (dùng chữ cái tên). Người dùng tự tải ảnh khi đăng nhập lần đầu.
  const [avatar, setAvatar] = useState(member?.avatar || '');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [uploadError, setUploadError] = useState<string>('');

  const handleLocalImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    if (!file.type.startsWith('image/')) {
      setUploadError('Tệp không đúng định dạng hình ảnh!');
      return;
    }
    if (file.size > 3 * 1024 * 1024) {
      setUploadError('Kích thước ảnh tối đa là 3MB!');
      return;
    }

    setUploadError('');
    const reader = new FileReader();
    reader.onload = async (event) => {
      if (event.target?.result) {
        // Thu nhỏ ảnh trước khi lưu để không vượt giới hạn dung lượng khi đồng bộ cloud
        setAvatar(await downscaleImage(event.target.result as string));
      }
    };
    reader.onerror = () => {
      setUploadError('Lỗi đọc file ảnh!');
    };
    reader.readAsDataURL(file);
  };

  const [errors, setErrors] = useState<{ hoTen?: string; username?: string; email?: string; customId?: string; pickedPerson?: string }>({});

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const newErrors: typeof errors = {};

    // TẠO MỚI: bắt buộc chọn 1 người thật từ danh bạ App Tổng, không gõ tay nữa.
    if (isNew) {
      if (!pickedPerson) {
        newErrors.pickedPerson = 'Vui lòng chọn 1 nhân sự từ danh bạ App Tổng';
      } else {
        // Phòng hờ: danh bạ có thể đã lỗi thời (người này vừa được thêm ở tab khác) —
        // API /api/staff-directory đã tự loại người đã có hồ sơ, đây chỉ là lớp bảo vệ thêm.
        const isDuplicate = existingStaff.some(s => s.id === pickedPerson.id);
        if (isDuplicate) {
          newErrors.pickedPerson = 'Người này đã có hồ sơ trong app — thử tải lại trang.';
        }
      }
    }

    const cleanId = customId.trim().toUpperCase();
    if (!isNew) {
      // CHỈNH SỬA: giữ nguyên hành vi cũ — Mã Nhân sự vẫn là ô gõ tay, sửa được.
      if (!cleanId) {
        newErrors.customId = 'Mã nhân viên không được để trống';
      } else {
        const isDuplicateId = existingStaff.some(s => s.id !== member?.id && s.id.toUpperCase() === cleanId);
        if (isDuplicateId) {
          newErrors.customId = 'Mã nhân viên này đã được sử dụng';
        }
      }

      if (!hoTen.trim()) {
        newErrors.hoTen = 'Họ tên không được để trống';
      }
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Level 2 khi TẠO MỚI chỉ được tạo Chuyên viên (Level 3) — ép chức danh & quyền để an toàn.
    const finalChucVu: ChucVu = (isManager && isNew) ? 'Chuyên viên đấu thầu' : chucVu;
    const finalRole = (isManager && isNew) ? 'STAFF' : role;
    const finalId = isNew ? pickedPerson!.id : cleanId;
    const finalHoTen = isNew ? pickedPerson!.name : hoTen.trim();

    onSave({
      id: finalId,
      hoTen: finalHoTen,
      chucVu: finalChucVu,
      avatar: member?.avatar || '',
      kpiDiem: member?.kpiDiem ?? 100,
      soDuAnDangLam: member?.soDuAnDangLam ?? 0,
      tiLeDungHan: member?.tiLeDungHan ?? 100,
      // Tên đăng nhập / email / mật khẩu / ảnh: do App Tổng quản.
      // TẠO MỚI lấy thẳng từ người vừa chọn (danh bạ App Tổng) — CHỈNH SỬA giữ nguyên
      // giá trị hiện có, app này không có ô nhập nữa (chị Trâm chốt 26/07/2026: sửa ở
      // đây đá với App Tổng).
      username: isNew ? pickedPerson!.username : member?.username,
      email: (isNew ? pickedPerson!.email : member?.email) ?? undefined,
      mustChangePassword: member?.mustChangePassword ?? false,
      role: finalRole,
      // Chỉ nhân viên (L3) mới thuộc đội ngũ của một Quản lý. Quản lý (L2) tự gán thì giữ nguyên giá trị cũ.
      quanLyPhuTrachId: finalRole === 'STAFF'
        ? (isManager ? member?.quanLyPhuTrachId : (quanLyPhuTrachId || undefined))
        : undefined,
    });
  };

  // Đồng bộ quyền theo chức danh (gợi ý mặc định)
  const handleChucVuChange = (val: ChucVu) => {
    setChucVu(val);
    setRole(chucVuToRole(val));
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-0 md:p-4 bg-slate-900/60 backdrop-blur-sm">
      {/* Mobile <768px: gần toàn màn hình (13-overlays/dialog.md); md+: hộp giữa màn hình */}
      <div ref={panelRef} role="dialog" aria-modal="true" aria-labelledby="staff-edit-title" tabIndex={-1} className="bg-white dark:bg-dark-card rounded-none md:rounded-xl border border-slate-200 dark:border-slate-800 shadow-2xl max-w-md w-full h-full md:h-auto flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-dark-card/50">
          <div className="flex items-center gap-2">
            <User className="w-5 h-5 text-brand-accent dark:text-brand-accent-300" />
            <h3 id="staff-edit-title" className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-tight">
              {isNew ? 'Thêm tài khoản nhân sự mới' : 'Chỉnh sửa tài khoản & Phân quyền'}
            </h3>
          </div>
          <button 
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-slate-100 dark:hover:bg-dark-elevated text-slate-400 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-5 space-y-4 flex-1 md:flex-none md:max-h-[80vh] overflow-y-auto">
          {/* Nhân sự: TẠO MỚI → chọn người thật từ danh bạ App Tổng (không gõ tay nữa,
              Sếp chốt 27/08/2026); CHỈNH SỬA → giữ nguyên 2 ô Mã NS + Họ Tên như trước. */}
          {isNew ? (
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Nhân sự (từ App Tổng) <span className="text-brand-danger">*</span>
              </label>
              <StaffDirectoryPicker
                value={pickedPerson}
                onChange={(p) => {
                  setPickedPerson(p);
                  if (errors.pickedPerson) setErrors(prev => ({ ...prev, pickedPerson: undefined }));
                }}
                error={errors.pickedPerson}
              />
            </div>
          ) : (
            <div className="grid grid-cols-3 gap-3">
              <div className="col-span-1">
                <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                  Mã Nhân sự <span className="text-brand-danger">*</span>
                </label>
                <input
                  type="text"
                  value={customId}
                  onChange={(e) => {
                    setCustomId(e.target.value);
                    if (errors.customId) setErrors(prev => ({ ...prev, customId: undefined }));
                  }}
                  placeholder="VD: NV01"
                  className={`w-full px-2.5 py-1.5 border rounded-lg text-xs font-mono font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 ${
                    errors.customId ? 'border-brand-danger/50 focus:ring-brand-danger' : 'border-slate-200 dark:border-slate-700 focus:ring-brand-accent'
                  }`}
                />
                {errors.customId && (
                  <span className="text-[9px] text-brand-danger mt-0.5 block font-medium leading-none">
                    {errors.customId}
                  </span>
                )}
              </div>
              <div className="col-span-2">
                <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                  Họ và Tên <span className="text-brand-danger">*</span>
                </label>
                <input
                  type="text"
                  value={hoTen}
                  onChange={(e) => {
                    setHoTen(e.target.value);
                    if (errors.hoTen) setErrors(prev => ({ ...prev, hoTen: undefined }));
                  }}
                  placeholder="Nguyễn Văn A"
                  className={`w-full px-2.5 py-1.5 border rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated ${
                    errors.hoTen ? 'border-brand-danger/50 focus:ring-brand-danger' : 'border-slate-200 dark:border-slate-700 focus:ring-brand-accent'
                  } focus:outline-none focus:ring-2`}
                />
                {errors.hoTen && (
                  <span className="text-[9px] text-brand-danger mt-0.5 block font-medium">
                    {errors.hoTen}
                  </span>
                )}
              </div>
            </div>
          )}

          {/* Row Chức vụ & Phân quyền */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Chức danh / Vị trí
              </label>
              <select
                value={(isManager && isNew) ? 'Chuyên viên đấu thầu' : chucVu}
                onChange={(e) => handleChucVuChange(e.target.value as ChucVu)}
                disabled={isManager}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent disabled:opacity-60 disabled:cursor-not-allowed"
              >
                <option value="Trưởng phòng">Trưởng phòng</option>
                <option value="Phó phòng">Phó phòng</option>
                <option value="Quản lý">Quản lý</option>
                <option value="Chuyên viên đấu thầu">Chuyên viên đấu thầu</option>
                <option value="Ban giám đốc">Ban giám đốc</option>
                <option value="Quản trị hệ thống">Quản trị hệ thống</option>
                {/* "Khách (chỉ xem)" là chức danh CŨ — chị Trâm chốt 17/08/2026 dùng "Ban giám đốc"
                    cho Level 4. Chỉ hiện lại option này khi bản ghi đang mang giá trị cũ, để
                    select không bị trống và Trưởng phòng thấy rõ cần đổi sang chức danh mới. */}
                {chucVu === 'Khách (chỉ xem)' && (
                  <option value="Khách (chỉ xem)">Khách (chỉ xem) — chức danh cũ, nên đổi thành Ban giám đốc</option>
                )}
              </select>
            </div>

            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Quyền hệ thống (RBAC)
              </label>
              <select
                value={(isManager && isNew) ? 'STAFF' : role}
                onChange={(e) => setRole(e.target.value as any)}
                disabled={isManager}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {/* Thang Level chị Trâm chốt 17/08/2026 — giữ khớp app/api/roles/route.ts */}
                <option value="BOOD">Level 1 - Trưởng phòng / Phó phòng / Quản trị</option>
                <option value="MANAGER">Level 2 - Quản lý</option>
                <option value="STAFF">Level 3 - Nhân viên</option>
                <option value="VIEWER">Level 4 - Ban giám đốc</option>
              </select>
              {isManager && (
                <p className="text-[9px] text-slate-400 mt-1 leading-tight">Quản lý chỉ tạo được tài khoản Chuyên viên (Level 3).</p>
              )}
            </div>
          </div>

          {/* Quản lý phụ trách (đội ngũ) — chỉ Trưởng phòng (L1) gán, chỉ cho nhân viên Level 3.
              Quyết định Quản lý nào được XEM đội ngũ & KPI của nhân viên này (không đổi việc giao việc). */}
          {!isManager && role === 'STAFF' && (
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Quản lý phụ trách (đội ngũ)
              </label>
              <select
                value={quanLyPhuTrachId}
                onChange={(e) => setQuanLyPhuTrachId(e.target.value)}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent"
              >
                <option value="">— Chưa gán (chỉ Trưởng phòng thấy) —</option>
                {managerOptions.map(m => {
                  const conLaQuanLy = (m.role || chucVuToRole(m.chucVu)) === 'MANAGER';
                  return (
                    <option key={m.id} value={m.id}>
                      {m.hoTen}{!conLaQuanLy ? ' — không còn là Quản lý, nên gán lại người khác' : ''}
                    </option>
                  );
                })}
              </select>
              <p className="text-[9px] text-slate-400 mt-1 leading-tight">
                Quản lý được gán sẽ thấy nhân viên này trong <b>Đội Ngũ &amp; KPI</b> và KPI Dashboard. Mỗi nhân viên chỉ thuộc 1 quản lý.
              </p>
            </div>
          )}

          {/* Chị Trâm chốt 17/08/2026: BỎ khối giải thích dài về phân quyền ở đây — nhìn rối và
              không chuyên nghiệp. Tên các Level ở ô chọn phía trên đã đủ nghĩa; chi tiết quyền hạn
              tra trong tài liệu bàn giao, không nhồi vào hộp thoại thêm nhân sự. */}

          {/* Actions */}
          <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100 dark:border-slate-800">
            <button 
              type="button"
              onClick={onClose}
              className="px-4 py-2 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-dark-elevated transition-colors"
            >
              Hủy bỏ
            </button>
            <button 
              type="submit"
              className="px-4 py-2 bg-brand-primary hover:bg-brand-primary-hover text-white rounded-lg text-xs font-black flex items-center gap-1.5 shadow-md transition-all cursor-pointer"
            >
              <Save className="w-3.5 h-3.5" />
              {isNew ? 'THÊM MỚI TÀI KHOẢN' : 'LƯU THAY ĐỔI'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
