import React, { useState, useRef } from 'react';
import { Staff } from '../types';
import { chucVuToRole } from '../App';
import { downscaleImage } from '../lib/firebase';
import { X, Save, User, Key, Mail, ShieldAlert, Upload } from 'lucide-react';
import { useModalA11y } from '../utils/useModalA11y';

type ChucVu = 'Ban giám đốc' | 'Trưởng phòng' | 'Phó phòng' | 'Quản lý' | 'Chuyên viên đấu thầu' | 'Quản trị hệ thống';

interface StaffEditModalProps {
  member?: Staff | null; // If null/undefined, we are adding a new account
  existingStaff: Staff[];
  currentUserRole?: 'BOOD' | 'MANAGER' | 'STAFF'; // vai trò người đang thao tác (để giới hạn quyền L2)
  onSave: (updated: Staff) => void;
  onClose: () => void;
}

export default function StaffEditModal({ member, existingStaff, currentUserRole, onSave, onClose }: StaffEditModalProps) {
  const panelRef = useModalA11y(onClose);
  const isNew = !member;
  // Level 2 (Quản lý) chỉ được tạo tài khoản Chuyên viên (Level 3) và KHÔNG được xem mật khẩu của người khác.
  const isManager = currentUserRole === 'MANAGER';

  // Auto-generate ID if it's a new account
  const autoGeneratedId = React.useMemo(() => {
    const ids = existingStaff.map(s => {
      const num = parseInt(s.id.replace('S', ''), 10);
      return isNaN(num) ? 0 : num;
    });
    const maxId = ids.length > 0 ? Math.max(...ids) : 0;
    const nextNum = maxId + 1;
    return `S${String(nextNum).padStart(3, '0')}`;
  }, [existingStaff]);

  const [customId, setCustomId] = useState(member?.id || autoGeneratedId);
  const [hoTen, setHoTen] = useState(member?.hoTen || '');
  const [chucVu, setChucVu] = useState<ChucVu>(
    member?.chucVu || 'Chuyên viên đấu thầu'
  );
  const [username, setUsername] = useState(member?.username || '');
  const [email, setEmail] = useState(member?.email || '');
  const [mustChangePassword, setMustChangePassword] = useState<boolean>(member?.mustChangePassword ?? isNew);
  const [role, setRole] = useState<'BOOD' | 'MANAGER' | 'STAFF'>(
    member?.role || chucVuToRole(member?.chucVu)
  );
  // Quản lý phụ trách (đội ngũ) — chỉ Trưởng phòng (L1) được gán, chỉ áp cho nhân viên Level 3.
  const [quanLyPhuTrachId, setQuanLyPhuTrachId] = useState<string>(member?.quanLyPhuTrachId || '');
  // Danh sách Quản lý (L2) còn làm việc để chọn
  const managerOptions = React.useMemo(
    () => existingStaff.filter(s => !s.daNghi && (s.role || chucVuToRole(s.chucVu)) === 'MANAGER'),
    [existingStaff]
  );

  // Ảnh đại diện: mặc định trống (dùng chữ cái tên). Người dùng tự tải ảnh khi đăng nhập lần đầu.
  const [avatar, setAvatar] = useState(member?.avatar || '');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [uploadError, setUploadError] = useState<string>('');

  const handleLocalImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    if (!file.type.startsWith('image/')) {
      setUploadError('Tệp không đúng định dạng hình ảnh!');
      return;
    }
    if (file.size > 3 * 1024 * 1024) {
      setUploadError('Kích thước ảnh tối đa là 3MB!');
      return;
    }

    setUploadError('');
    const reader = new FileReader();
    reader.onload = async (event) => {
      if (event.target?.result) {
        // Thu nhỏ ảnh trước khi lưu để không vượt giới hạn dung lượng khi đồng bộ cloud
        setAvatar(await downscaleImage(event.target.result as string));
      }
    };
    reader.onerror = () => {
      setUploadError('Lỗi đọc file ảnh!');
    };
    reader.readAsDataURL(file);
  };

  const [errors, setErrors] = useState<{ hoTen?: string; username?: string; email?: string; customId?: string }>({});

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const newErrors: typeof errors = {};
    const cleanId = customId.trim().toUpperCase();

    if (!cleanId) {
      newErrors.customId = 'Mã nhân viên không được để trống';
    } else {
      const isDuplicateId = existingStaff.some(s => s.id !== member?.id && s.id.toUpperCase() === cleanId);
      if (isDuplicateId) {
        newErrors.customId = 'Mã nhân viên này đã được sử dụng';
      }
    }

    if (!hoTen.trim()) {
      newErrors.hoTen = 'Họ tên không được để trống';
    }

    // Tên đăng nhập: bắt buộc, không trùng (không phân biệt hoa/thường)
    const cleanUsername = username.trim();
    if (!cleanUsername) {
      newErrors.username = 'Tên đăng nhập không được để trống';
    } else if (/\s/.test(cleanUsername)) {
      newErrors.username = 'Tên đăng nhập không được chứa khoảng trắng';
    } else {
      const isDupUser = existingStaff.some(s => s.id !== member?.id && s.username?.toLowerCase() === cleanUsername.toLowerCase());
      if (isDupUser) newErrors.username = 'Tên đăng nhập này đã được sử dụng';
    }

    // Email: tùy chọn — chỉ kiểm tra khi có nhập
    if (email.trim()) {
      if (!/\S+@\S+\.\S+/.test(email)) {
        newErrors.email = 'Email không hợp lệ (Ví dụ: ten@hpcons.vn)';
      } else {
        const isDuplicate = existingStaff.some(s => s.id !== member?.id && s.email && s.email.toLowerCase() === email.trim().toLowerCase());
        if (isDuplicate) {
          newErrors.email = 'Email này đã được sử dụng bởi một tài khoản khác';
        }
      }
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Level 2 khi TẠO MỚI chỉ được tạo Chuyên viên (Level 3) — ép chức danh & quyền để an toàn.
    const finalChucVu: ChucVu = (isManager && isNew) ? 'Chuyên viên đấu thầu' : chucVu;
    const finalRole = (isManager && isNew) ? 'STAFF' : role;

    onSave({
      id: cleanId,
      hoTen: hoTen.trim(),
      chucVu: finalChucVu,
      avatar: avatar.trim(),
      kpiDiem: member?.kpiDiem ?? 100,
      soDuAnDangLam: member?.soDuAnDangLam ?? 0,
      tiLeDungHan: member?.tiLeDungHan ?? 100,
      username: cleanUsername,
      email: email.trim().toLowerCase(),
      mustChangePassword: mustChangePassword,
      role: finalRole,
      // Chỉ nhân viên (L3) mới thuộc đội ngũ của một Quản lý. Quản lý (L2) tự gán thì giữ nguyên giá trị cũ.
      quanLyPhuTrachId: finalRole === 'STAFF'
        ? (isManager ? member?.quanLyPhuTrachId : (quanLyPhuTrachId || undefined))
        : undefined,
    });
  };

  // Đồng bộ quyền theo chức danh (gợi ý mặc định)
  const handleChucVuChange = (val: ChucVu) => {
    setChucVu(val);
    setRole(chucVuToRole(val));
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-0 md:p-4 bg-slate-900/60 backdrop-blur-sm">
      {/* Mobile <768px: gần toàn màn hình (13-overlays/dialog.md); md+: hộp giữa màn hình */}
      <div ref={panelRef} role="dialog" aria-modal="true" aria-labelledby="staff-edit-title" tabIndex={-1} className="bg-white dark:bg-dark-card rounded-none md:rounded-xl border border-slate-200 dark:border-slate-800 shadow-2xl max-w-md w-full h-full md:h-auto flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-dark-card/50">
          <div className="flex items-center gap-2">
            <User className="w-5 h-5 text-brand-accent dark:text-brand-accent-300" />
            <h3 id="staff-edit-title" className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-tight">
              {isNew ? 'Thêm tài khoản nhân sự mới' : 'Chỉnh sửa tài khoản & Phân quyền'}
            </h3>
          </div>
          <button 
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-slate-100 dark:hover:bg-dark-elevated text-slate-400 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-5 space-y-4 flex-1 md:flex-none md:max-h-[80vh] overflow-y-auto">
          {/* Row ID & Name */}
          <div className="grid grid-cols-3 gap-3">
            <div className="col-span-1">
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Mã Nhân sự <span className="text-brand-danger">*</span>
              </label>
              <input 
                type="text" 
                value={customId} 
                onChange={(e) => {
                  setCustomId(e.target.value);
                  if (errors.customId) setErrors(prev => ({ ...prev, customId: undefined }));
                }}
                placeholder="VD: NV01"
                className={`w-full px-2.5 py-1.5 border rounded-lg text-xs font-mono font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 ${
                  errors.customId ? 'border-brand-danger/50 focus:ring-brand-danger' : 'border-slate-200 dark:border-slate-700 focus:ring-brand-accent'
                }`}
              />
              {errors.customId && (
                <span className="text-[9px] text-brand-danger mt-0.5 block font-medium leading-none">
                  {errors.customId}
                </span>
              )}
            </div>
            <div className="col-span-2">
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Họ và Tên <span className="text-brand-danger">*</span>
              </label>
              <input 
                type="text" 
                value={hoTen} 
                onChange={(e) => {
                  setHoTen(e.target.value);
                  if (errors.hoTen) setErrors(prev => ({ ...prev, hoTen: undefined }));
                }}
                placeholder="Nguyễn Văn A"
                className={`w-full px-2.5 py-1.5 border rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated ${
                  errors.hoTen ? 'border-brand-danger/50 focus:ring-brand-danger' : 'border-slate-200 dark:border-slate-700 focus:ring-brand-accent'
                } focus:outline-none focus:ring-2`}
              />
              {errors.hoTen && (
                <span className="text-[9px] text-brand-danger mt-0.5 block font-medium">
                  {errors.hoTen}
                </span>
              )}
            </div>
          </div>

          {/* Row Chức vụ & Phân quyền */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Chức danh / Vị trí
              </label>
              <select
                value={(isManager && isNew) ? 'Chuyên viên đấu thầu' : chucVu}
                onChange={(e) => handleChucVuChange(e.target.value as ChucVu)}
                disabled={isManager}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent disabled:opacity-60 disabled:cursor-not-allowed"
              >
                <option value="Ban giám đốc">Ban giám đốc</option>
                <option value="Trưởng phòng">Trưởng phòng</option>
                <option value="Phó phòng">Phó phòng</option>
                <option value="Quản lý">Quản lý</option>
                <option value="Chuyên viên đấu thầu">Chuyên viên đấu thầu</option>
                <option value="Quản trị hệ thống">Quản trị hệ thống</option>
              </select>
            </div>

            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Quyền hệ thống (RBAC)
              </label>
              <select
                value={(isManager && isNew) ? 'STAFF' : role}
                onChange={(e) => setRole(e.target.value as any)}
                disabled={isManager}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent disabled:opacity-60 disabled:cursor-not-allowed"
              >
                <option value="BOOD">Level 1 - Ban Giám đốc / Trưởng phòng / Phó phòng / Quản trị</option>
                <option value="MANAGER">Level 2 - Quản lý</option>
                <option value="STAFF">Level 3 - Nhân sự (Chuyên viên)</option>
              </select>
              {isManager && (
                <p className="text-[9px] text-slate-400 mt-1 leading-tight">Quản lý chỉ tạo được tài khoản Chuyên viên (Level 3).</p>
              )}
            </div>
          </div>

          {/* Quản lý phụ trách (đội ngũ) — chỉ Trưởng phòng (L1) gán, chỉ cho nhân viên Level 3.
              Quyết định Quản lý nào được XEM đội ngũ & KPI của nhân viên này (không đổi việc giao việc). */}
          {!isManager && role === 'STAFF' && (
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Quản lý phụ trách (đội ngũ)
              </label>
              <select
                value={quanLyPhuTrachId}
                onChange={(e) => setQuanLyPhuTrachId(e.target.value)}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent"
              >
                <option value="">— Chưa gán (chỉ Trưởng phòng thấy) —</option>
                {managerOptions.map(m => (
                  <option key={m.id} value={m.id}>{m.hoTen}</option>
                ))}
              </select>
              <p className="text-[9px] text-slate-400 mt-1 leading-tight">
                Quản lý được gán sẽ thấy nhân viên này trong <b>Đội Ngũ &amp; KPI</b> và KPI Dashboard. Mỗi nhân viên chỉ thuộc 1 quản lý.
              </p>
            </div>
          )}

          {/* Username (login) */}
          <div>
            <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1 flex items-center gap-1">
              <User className="w-3 h-3 text-slate-400" />
              Tên đăng nhập <span className="text-brand-danger">*</span>
            </label>
            <input
              type="text"
              value={username}
              onChange={(e) => {
                setUsername(e.target.value);
                if (errors.username) setErrors(prev => ({ ...prev, username: undefined }));
              }}
              placeholder="vd: nam.pham"
              autoComplete="off"
              className={`w-full px-2.5 py-1.5 border rounded-lg text-xs font-mono font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated ${
                errors.username ? 'border-brand-danger/50 focus:ring-brand-danger' : 'border-slate-200 dark:border-slate-700 focus:ring-brand-accent'
              } focus:outline-none focus:ring-2`}
            />
            {errors.username && (
              <span className="text-[9px] text-brand-danger mt-0.5 block font-medium">
                {errors.username}
              </span>
            )}
          </div>

          {/* Email Account (optional) */}
          <div>
            <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1 flex items-center gap-1">
              <Mail className="w-3 h-3 text-slate-400" />
              Email <span className="text-slate-400 normal-case font-medium">(tùy chọn — cũng dùng để đăng nhập)</span>
            </label>
            <input
              type="text"
              value={email}
              onChange={(e) => {
                setEmail(e.target.value);
                if (errors.email) setErrors(prev => ({ ...prev, email: undefined }));
              }}
              placeholder="nhanvien@hpcons.vn"
              className={`w-full px-2.5 py-1.5 border rounded-lg text-xs font-mono font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated ${
                errors.email ? 'border-brand-danger/50 focus:ring-brand-danger' : 'border-slate-200 dark:border-slate-700 focus:ring-brand-accent'
              } focus:outline-none focus:ring-2`}
            />
            {errors.email && (
              <span className="text-[9px] text-brand-danger mt-0.5 block font-medium">
                {errors.email}
              </span>
            )}
          </div>

          {/* Mật khẩu: Firebase quản lý (đã mã hóa) — hệ thống không lưu, không hiển thị */}
          <div>
            <label className="text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 flex items-center gap-1 mb-1">
              <Key className="w-3 h-3 text-slate-400" />
              Mật khẩu truy cập
            </label>
            <div className="w-full px-3 py-2 border border-slate-200 dark:border-slate-700 rounded-lg text-[10px] font-medium text-slate-500 dark:text-slate-400 bg-slate-50 dark:bg-dark-bg leading-relaxed">
              🔐 Mật khẩu do hệ thống Firebase quản lý (đã mã hóa) — không ai xem được, kể cả quản trị viên.
              {isNew && <><br />Tài khoản mới <b className="text-slate-700 dark:text-slate-200">tự kích hoạt</b> khi đăng nhập lần đầu bằng mật khẩu mặc định <b className="text-brand-accent dark:text-brand-accent-300">123456</b>.</>}
            </div>
            <label className="flex items-center gap-2 mt-2 cursor-pointer select-none">
              <input
                type="checkbox"
                checked={mustChangePassword}
                onChange={(e) => setMustChangePassword(e.target.checked)}
                className="w-3.5 h-3.5 rounded border-slate-300 dark:border-slate-600 text-brand-accent focus:ring-brand-accent"
              />
              <span className="text-[10px] font-bold text-slate-600 dark:text-slate-300">
                Bắt buộc thêm ảnh &amp; đổi mật khẩu ở lần đăng nhập tới
              </span>
            </label>
          </div>

          {/* Avatar Selector */}
          <div className="border-t border-slate-100 dark:border-slate-850 pt-3">
            <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1.5 flex items-center gap-1">
              📷 Chọn ảnh đại diện (Tải từ máy tính hoặc dùng link URL)
            </label>
            <div className="flex gap-2.5 items-center mb-2.5">
              <div
                className="relative group w-11 h-11 rounded-full border-2 border-slate-200 dark:border-slate-700 overflow-hidden cursor-pointer shrink-0 bg-slate-100 dark:bg-dark-elevated flex items-center justify-center"
                onClick={() => fileInputRef.current?.click()}
                title="Nhấp để tải ảnh từ máy tính của bạn"
              >
                {avatar ? (
                  <img
                    src={avatar}
                    alt="Ảnh đại diện"
                    className="w-full h-full object-cover transition-all group-hover:scale-105"
                  />
                ) : (
                  <span className="text-xs font-black text-slate-400 dark:text-slate-500 uppercase">
                    {(hoTen.trim().split(/\s+/).pop()?.[0] || '') + (hoTen.trim().split(/\s+/)[0]?.[0] || '') || '?'}
                  </span>
                )}
                <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <Upload className="w-3 h-3 text-white" />
                </div>
              </div>
              <div className="flex-1 space-y-1.5">
                <div className="flex gap-1.5">
                  <input 
                    type="text" 
                    value={avatar} 
                    onChange={(e) => setAvatar(e.target.value)}
                    placeholder="Nhập link URL ảnh đại diện hoặc upload..."
                    className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent font-mono"
                  />
                  <button
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="px-2.5 py-1.5 bg-brand-accent/10 hover:bg-brand-accent/15 dark:bg-brand-accent/15 dark:hover:bg-brand-accent/15 text-brand-accent dark:text-brand-accent-300 rounded-lg text-xs font-bold shrink-0 transition-all flex items-center gap-1 border border-brand-accent/50 dark:border-brand-accent/30 cursor-pointer"
                  >
                    <Upload className="w-3 h-3" />
                    Tải từ máy
                  </button>
                </div>
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleLocalImageUpload}
                  accept="image/*"
                  className="hidden" 
                />
              </div>
            </div>

            {uploadError && (
              <p className="text-[10px] text-brand-danger font-bold mb-2 animate-pulse">
                ⚠️ {uploadError}
              </p>
            )}
          </div>

          <div className="bg-slate-50 dark:bg-dark-card/40 p-3 rounded-lg border border-slate-100 dark:border-slate-800 text-[10px] text-slate-500 dark:text-slate-400 leading-relaxed font-medium flex gap-2 items-start">
            <ShieldAlert className="w-4 h-4 text-brand-accent shrink-0 mt-0.5" />
            <div>
              <strong>Thông tin kiểm tra bảo mật (IT Specialist Check):</strong> 
              <ul className="list-disc pl-4 mt-1 space-y-0.5">
                <li><strong>Level 1 (BOOD):</strong> Toàn quyền phê duyệt dời hạn và xem tất cả dự án.</li>
                <li><strong>Level 2 (MANAGER):</strong> Chỉ quản lý, chỉnh sửa, gán việc cho nhóm.</li>
                <li><strong>Level 3 (STAFF):</strong> Chỉ cập nhật tiến độ bóc BOQ được phân bổ.</li>
              </ul>
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100 dark:border-slate-800">
            <button 
              type="button"
              onClick={onClose}
              className="px-4 py-2 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-dark-elevated transition-colors"
            >
              Hủy bỏ
            </button>
            <button 
              type="submit"
              className="px-4 py-2 bg-brand-primary hover:bg-brand-primary-hover text-white rounded-lg text-xs font-black flex items-center gap-1.5 shadow-md transition-all cursor-pointer"
            >
              <Save className="w-3.5 h-3.5" />
              {isNew ? 'THÊM MỚI TÀI KHOẢN' : 'LƯU THAY ĐỔI'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
