import React, { useState, useRef } from 'react';
import { Staff } from '../types';
import { chucVuToRole } from '../App';
import { downscaleImage } from '../lib/firebase';
import { X, Save, User } from 'lucide-react';
import { useModalA11y } from '../utils/useModalA11y';
import StaffDirectoryPicker, { DirectoryPerson } from './StaffDirectoryPicker';
import { CHUC_VU_BY_ROLE, NHAN_LEVEL, lyDoKhoaLevel } from '../lib/phanQuyenLevel';

type ChucVu = 'Ban giám đốc' | 'Trưởng phòng' | 'Phó phòng' | 'Quản lý' | 'Chuyên viên đấu thầu' | 'Quản trị hệ thống' | 'Khách (chỉ xem)';

interface StaffEditModalProps {
  member?: Staff | null; // If null/undefined, we are adding a new account
  existingStaff: Staff[];
  currentUserRole?: 'BOOD' | 'MANAGER' | 'STAFF' | 'VIEWER'; // vai trò người đang thao tác (để giới hạn quyền L2)
  currentUserId?: string; // uid người đang thao tác — khoá ô level của chính mình
  ownerIds?: string[]; // uid owner App Tổng (GET /api/phan-quyen/level) — owner chỉ đổi ở App Tổng
  // levelDaDoi: level vừa được ĐỔI QUA MÁY CHỦ (route /api/phan-quyen/level, đã ghi về App Tổng).
  // Không có = level không đổi, nơi nhận PHẢI giữ nguyên role đang có (không lấy role từ modal).
  onSave: (updated: Staff, levelDaDoi?: { levelCu: string; levelMoi: string }) => void;
  onClose: () => void;
}

export default function StaffEditModal({ member, existingStaff, currentUserRole, currentUserId, ownerIds = [], onSave, onClose }: StaffEditModalProps) {
  const panelRef = useModalA11y(onClose);
  const isNew = !member;
  // Level 2 (Quản lý) chỉ được tạo tài khoản Chuyên viên (Level 3) và KHÔNG được xem mật khẩu của người khác.
  const isManager = currentUserRole === 'MANAGER';

  // Auto-generate ID if it's a new account
  const autoGeneratedId = React.useMemo(() => {
    const ids = existingStaff.map(s => {
      const num = parseInt(s.id.replace('S', ''), 10);
      return isNaN(num) ? 0 : num;
    });
    const maxId = ids.length > 0 ? Math.max(...ids) : 0;
    const nextNum = maxId + 1;
    return `S${String(nextNum).padStart(3, '0')}`;
  }, [existingStaff]);

  const [customId, setCustomId] = useState(member?.id || autoGeneratedId);
  // Chỉ đọc khi CHỈNH SỬA (hiển thị giá trị hiện tại — luôn đồng bộ sống từ App Tổng ở
  // route SSO, không sửa tay được ở đây nữa). Khi TẠO MỚI thì lấy từ pickedPerson.
  const hoTen = member?.hoTen || '';
  // Nhân sự chọn từ danh bạ App Tổng (chỉ dùng khi isNew) — thay cho gõ tay Mã Nhân sự
  // + Họ và Tên (Sếp chốt 27/08/2026). id = uid App Tổng, TRÙNG khoá staff/{uid} mà
  // route SSO sẽ dùng khi chính người đó tự đăng nhập sau này — tránh tạo trùng hồ sơ.
  const [pickedPerson, setPickedPerson] = useState<DirectoryPerson | null>(null);
  const levelTaoMoi = pickedPerson?.levelAppTong ?? null;
  const [chucVu, setChucVu] = useState<ChucVu>(
    member?.chucVu || 'Chuyên viên đấu thầu'
  );
  const [username, setUsername] = useState(member?.username || '');
  const [email, setEmail] = useState(member?.email || '');
  const [mustChangePassword, setMustChangePassword] = useState<boolean>(member?.mustChangePassword ?? isNew);
  // ===== LEVEL: APP TỔNG LÀ NGUỒN DUY NHẤT (Sếp duyệt demo 28/09/2026) =====
  // Demo: tong-quan-demo/HPCons-DauThau/phan-quyen-theo-app-tong-2026-09-28/index.html
  // · CHỈNH SỬA: đổi level gọi route máy chủ /api/phan-quyen/level (ghi thẳng app_permissions ở
  //   App Tổng), không tự ghi `role` qua Firestore từ trình duyệt nữa. Chỉ chọn được Level 2/3/4.
  //   Khoá (kèm lý do) khi người xem không phải Trưởng phòng/owner, dòng của chính mình, hoặc người
  //   đích là Level 1 / owner — máy chủ vẫn kiểm lại bằng dữ liệu sống.
  // · TẠO MỚI: level lấy ĐÚNG level App Tổng của người được chọn, không cho tự đặt.
  const roleGoc: 'BOOD' | 'MANAGER' | 'STAFF' | 'VIEWER' = member?.role || chucVuToRole(member?.chucVu);
  const [role, setRole] = useState<'BOOD' | 'MANAGER' | 'STAFF' | 'VIEWER'>(roleGoc);
  const lyDoKhoa = isNew ? '' : lyDoKhoaLevel({
    nguoiXemRole: currentUserRole,
    nguoiXemLaOwner: !!currentUserId && ownerIds.includes(currentUserId),
    nguoiXemUid: currentUserId,
    nguoiDichUid: member!.id,
    nguoiDichRole: roleGoc,
    nguoiDichLaOwner: ownerIds.includes(member!.id),
  });
  const [dangLuu, setDangLuu] = useState(false);
  const [loiLevel, setLoiLevel] = useState('');
  // Quản lý phụ trách (đội ngũ) — chỉ Trưởng phòng (L1) được gán, chỉ áp cho nhân viên Level 3.
  const [quanLyPhuTrachId, setQuanLyPhuTrachId] = useState<string>(member?.quanLyPhuTrachId || '');
  // Danh sách Quản lý (L2) còn làm việc để chọn.
  // Người ĐANG được gán nhưng không còn là Quản lý (vừa lên Trưởng phòng, đổi quyền khác, hoặc
  // nghỉ việc) vẫn được giữ trong danh sách để select hiện ĐÚNG người đang gán, không tụt về
  // "Chưa gán" khiến Trưởng phòng tưởng dữ liệu mất (chị Trâm báo 28/07/2026 — dữ liệu vẫn còn
  // nguyên, chỉ là dropdown lọc theo role hiện tại nên không tìm thấy option khớp).
  const managerOptions = React.useMemo(() => {
    const list = existingStaff.filter(s => !s.daNghi && (s.role || chucVuToRole(s.chucVu)) === 'MANAGER');
    const dangGanId = member?.quanLyPhuTrachId;
    if (dangGanId && !list.some(s => s.id === dangGanId)) {
      const nguoiDangGan = existingStaff.find(s => s.id === dangGanId);
      if (nguoiDangGan) list.push(nguoiDangGan);
    }
    return list;
  }, [existingStaff, member?.quanLyPhuTrachId]);

  // Ảnh đại diện: mặc định trống (dùng chữ cái tên). Người dùng tự tải ảnh khi đăng nhập lần đầu.
  const [avatar, setAvatar] = useState(member?.avatar || '');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [uploadError, setUploadError] = useState<string>('');

  const handleLocalImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    if (!file.type.startsWith('image/')) {
      setUploadError('Tệp không đúng định dạng hình ảnh!');
      return;
    }
    if (file.size > 3 * 1024 * 1024) {
      setUploadError('Kích thước ảnh tối đa là 3MB!');
      return;
    }

    setUploadError('');
    const reader = new FileReader();
    reader.onload = async (event) => {
      if (event.target?.result) {
        // Thu nhỏ ảnh trước khi lưu để không vượt giới hạn dung lượng khi đồng bộ cloud
        setAvatar(await downscaleImage(event.target.result as string));
      }
    };
    reader.onerror = () => {
      setUploadError('Lỗi đọc file ảnh!');
    };
    reader.readAsDataURL(file);
  };

  const [errors, setErrors] = useState<{ hoTen?: string; username?: string; email?: string; customId?: string; pickedPerson?: string }>({});

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (dangLuu) return;
    setLoiLevel('');
    const newErrors: typeof errors = {};

    // TẠO MỚI: bắt buộc chọn 1 người thật từ danh bạ App Tổng, không gõ tay nữa.
    if (isNew) {
      if (!pickedPerson) {
        newErrors.pickedPerson = 'Vui lòng chọn 1 nhân sự từ danh bạ App Tổng';
      } else {
        // Phòng hờ: danh bạ có thể đã lỗi thời (người này vừa được thêm ở tab khác) —
        // API /api/staff-directory đã tự loại người đã có hồ sơ, đây chỉ là lớp bảo vệ
        // thêm. Khớp cả email/username ngoài id — hồ sơ CŨ tạo tay trước PR này mang mã
        // kiểu "S009" (không phải uid App Tổng) nên không khớp theo id (CodeRabbit góp ý
        // 27/08/2026, cùng gốc bug với phía server).
        const email = pickedPerson.email?.trim().toLowerCase();
        const username = pickedPerson.username?.trim().toLowerCase();
        const isDuplicate = existingStaff.some(s =>
          s.id === pickedPerson.id ||
          (!!email && s.email?.trim().toLowerCase() === email) ||
          (!!username && s.username?.trim().toLowerCase() === username)
        );
        if (isDuplicate) {
          newErrors.pickedPerson = 'Người này đã có hồ sơ trong app — thử tải lại trang.';
        } else if (!pickedPerson.levelAppTong) {
          // Cấp quyền vào app cho người mới là việc của App Tổng (demo 28/09/2026).
          newErrors.pickedPerson = 'Người này chưa được cấp quyền app Đấu thầu ở App Tổng — nhờ owner cấp ở account.hpcore.vn trước.';
        } else if (isManager && pickedPerson.levelAppTong !== 'STAFF') {
          newErrors.pickedPerson = 'Quản lý chỉ thêm được người có Level 3 (Chuyên viên) ở App Tổng.';
        }
      }
    }

    const cleanId = customId.trim().toUpperCase();
    if (!isNew) {
      // CHỈNH SỬA: Mã Nhân sự vẫn là ô gõ tay, sửa được như cũ. Họ và Tên giờ CHỈ ĐỌC
      // (đồng bộ từ App Tổng, xem JSX phía trên) nên không còn validate ở đây nữa.
      if (!cleanId) {
        newErrors.customId = 'Mã nhân viên không được để trống';
      } else {
        const isDuplicateId = existingStaff.some(s => s.id !== member?.id && s.id.toUpperCase() === cleanId);
        if (isDuplicateId) {
          newErrors.customId = 'Mã nhân viên này đã được sử dụng';
        }
      }
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // TẠO MỚI: level = level App Tổng của người được chọn (đã kiểm có ở trên).
    // CHỈNH SỬA: level đổi → gọi máy chủ ghi về App Tổng TRƯỚC, lấy role/chucVu máy chủ trả về.
    let finalRole: 'BOOD' | 'MANAGER' | 'STAFF' | 'VIEWER' = isNew ? levelTaoMoi! : roleGoc;
    let finalChucVu: ChucVu = (isManager && isNew) ? (CHUC_VU_BY_ROLE[finalRole] as ChucVu) : chucVu;
    let levelDaDoi: { levelCu: string; levelMoi: string } | undefined;
    if (!isNew && role !== roleGoc) {
      if (lyDoKhoa) { setLoiLevel(lyDoKhoa); return; }
      setDangLuu(true);
      try {
        const res = await fetch('/api/phan-quyen/level', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ uid: member!.id, level: role }),
        });
        const data = await res.json().catch(() => ({}));
        if (!res.ok || !data?.ok) {
          setLoiLevel(data?.message || `Không đổi được level (lỗi ${res.status}).`);
          setDangLuu(false);
          return;
        }
        finalRole = data.role;
        // Trưởng phòng tự đổi chức vụ trong cùng lần lưu → giữ chữ đó; không thì theo máy chủ.
        if (chucVu === (member?.chucVu || 'Chuyên viên đấu thầu') && data.chucVu) finalChucVu = data.chucVu as ChucVu;
        levelDaDoi = { levelCu: data.levelCu, levelMoi: data.levelMoi };
      } catch {
        setLoiLevel('Mất kết nối, chưa đổi được level. Vui lòng thử lại.');
        setDangLuu(false);
        return;
      }
      setDangLuu(false);
    }
    const finalId = isNew ? pickedPerson!.id : cleanId;
    const finalHoTen = isNew ? pickedPerson!.name : hoTen.trim();

    onSave({
      id: finalId,
      hoTen: finalHoTen,
      chucVu: finalChucVu,
      avatar: member?.avatar || '',
      kpiDiem: member?.kpiDiem ?? 100,
      soDuAnDangLam: member?.soDuAnDangLam ?? 0,
      tiLeDungHan: member?.tiLeDungHan ?? 100,
      // Tên đăng nhập / email / mật khẩu / ảnh: do App Tổng quản.
      // TẠO MỚI lấy thẳng từ người vừa chọn (danh bạ App Tổng) — CHỈNH SỬA giữ nguyên
      // giá trị hiện có, app này không có ô nhập nữa (chị Trâm chốt 26/07/2026: sửa ở
      // đây đá với App Tổng).
      username: isNew ? pickedPerson!.username : member?.username,
      email: (isNew ? pickedPerson!.email : member?.email) ?? undefined,
      mustChangePassword: member?.mustChangePassword ?? false,
      role: finalRole,
      // Chỉ nhân viên (L3) mới thuộc đội ngũ của một Quản lý. Quản lý (L2) tự gán thì giữ nguyên giá trị cũ.
      quanLyPhuTrachId: finalRole === 'STAFF'
        ? (isManager ? member?.quanLyPhuTrachId : (quanLyPhuTrachId || undefined))
        : undefined,
    }, levelDaDoi);
  };

  // Chức danh KHÔNG còn tự kéo level theo (28/09/2026): level do App Tổng giữ, chỉ đổi qua ô Level.
  const handleChucVuChange = (val: ChucVu) => {
    setChucVu(val);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-0 md:p-4 bg-slate-900/60 backdrop-blur-sm">
      {/* Mobile <768px: gần toàn màn hình (13-overlays/dialog.md); md+: hộp giữa màn hình */}
      <div ref={panelRef} role="dialog" aria-modal="true" aria-labelledby="staff-edit-title" tabIndex={-1} className="bg-white dark:bg-dark-card rounded-none md:rounded-xl border border-slate-200 dark:border-slate-800 shadow-2xl max-w-md w-full h-full md:h-auto flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-dark-card/50">
          <div className="flex items-center gap-2">
            <User className="w-5 h-5 text-brand-accent dark:text-brand-accent-300" />
            <h3 id="staff-edit-title" className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-tight">
              {isNew ? 'Thêm tài khoản nhân sự mới' : 'Chỉnh sửa tài khoản & Phân quyền'}
            </h3>
          </div>
          <button 
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-slate-100 dark:hover:bg-dark-elevated text-slate-400 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-5 space-y-4 flex-1 md:flex-none md:max-h-[80vh] overflow-y-auto">
          {/* Nhân sự: TẠO MỚI → chọn người thật từ danh bạ App Tổng (không gõ tay nữa,
              Sếp chốt 27/08/2026); CHỈNH SỬA → giữ nguyên 2 ô Mã NS + Họ Tên như trước. */}
          {isNew ? (
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Nhân sự (từ App Tổng) <span className="text-brand-danger">*</span>
              </label>
              <StaffDirectoryPicker
                value={pickedPerson}
                onChange={(p) => {
                  setPickedPerson(p);
                  // Chức danh gợi ý theo level App Tổng của người vừa chọn.
                  if (p?.levelAppTong) setChucVu(CHUC_VU_BY_ROLE[p.levelAppTong] as ChucVu);
                  if (errors.pickedPerson) setErrors(prev => ({ ...prev, pickedPerson: undefined }));
                }}
                error={errors.pickedPerson}
              />
            </div>
          ) : (
            <div className="grid grid-cols-3 gap-3">
              <div className="col-span-1">
                <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                  Mã Nhân sự <span className="text-brand-danger">*</span>
                </label>
                <input
                  type="text"
                  value={customId}
                  onChange={(e) => {
                    setCustomId(e.target.value);
                    if (errors.customId) setErrors(prev => ({ ...prev, customId: undefined }));
                  }}
                  placeholder="VD: NV01"
                  className={`w-full px-2.5 py-1.5 border rounded-lg text-xs font-mono font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 ${
                    errors.customId ? 'border-brand-danger/50 focus:ring-brand-danger' : 'border-slate-200 dark:border-slate-700 focus:ring-brand-accent'
                  }`}
                />
                {errors.customId && (
                  <span className="text-[9px] text-brand-danger mt-0.5 block font-medium leading-none">
                    {errors.customId}
                  </span>
                )}
              </div>
              <div className="col-span-2">
                <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                  Họ và Tên
                </label>
                {/* CHỈ ĐỌC (Sếp chốt 27/08/2026): họ tên giờ luôn đồng bộ SỐNG từ App Tổng ở
                    mỗi lần đăng nhập (xem app/api/auth/hpcore-session/route.ts) — cho sửa tay
                    ở đây sẽ là 1 cái bẫy UX: Trưởng phòng sửa xong tưởng đã lưu, nhưng lần
                    người này đăng nhập kế tiếp là bị ghi đè lại ngay. */}
                <div className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-500 dark:text-slate-400 bg-slate-50 dark:bg-dark-elevated/50">
                  {hoTen || '—'}
                </div>
                <p className="text-[9px] text-slate-400 mt-1 leading-tight">
                  Đồng bộ tự động từ App Tổng — không sửa được ở đây. Sai tên thì sửa ở
                  account.hpcore.vn/profile, tên sẽ tự cập nhật vào lần đăng nhập kế tiếp.
                </p>
              </div>
            </div>
          )}

          {/* Row Chức vụ & Phân quyền */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Chức danh / Vị trí
              </label>
              <select
                value={(isManager && isNew) ? 'Chuyên viên đấu thầu' : chucVu}
                onChange={(e) => handleChucVuChange(e.target.value as ChucVu)}
                disabled={isManager}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent disabled:opacity-60 disabled:cursor-not-allowed"
              >
                <option value="Trưởng phòng">Trưởng phòng</option>
                <option value="Phó phòng">Phó phòng</option>
                <option value="Quản lý">Quản lý</option>
                <option value="Chuyên viên đấu thầu">Chuyên viên đấu thầu</option>
                <option value="Ban giám đốc">Ban giám đốc</option>
                <option value="Quản trị hệ thống">Quản trị hệ thống</option>
                {/* "Khách (chỉ xem)" là chức danh CŨ — chị Trâm chốt 17/08/2026 dùng "Ban giám đốc"
                    cho Level 4. Chỉ hiện lại option này khi bản ghi đang mang giá trị cũ, để
                    select không bị trống và Trưởng phòng thấy rõ cần đổi sang chức danh mới. */}
                {chucVu === 'Khách (chỉ xem)' && (
                  <option value="Khách (chỉ xem)">Khách (chỉ xem) — chức danh cũ, nên đổi thành Ban giám đốc</option>
                )}
              </select>
            </div>

            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Quyền hệ thống (RBAC)
              </label>
              {isNew ? (
                // TẠO MỚI: chỉ hiện level App Tổng của người được chọn — không tự đặt.
                <div className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-500 dark:text-slate-400 bg-slate-50 dark:bg-dark-elevated/50">
                  {levelTaoMoi ? NHAN_LEVEL[levelTaoMoi] : (pickedPerson ? 'Chưa có quyền ở App Tổng' : '— chọn nhân sự —')}
                </div>
              ) : (
              <select
                value={role}
                onChange={(e) => { setRole(e.target.value as any); setLoiLevel(''); }}
                disabled={!!lyDoKhoa || dangLuu}
                title={lyDoKhoa || undefined}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {/* Thang Level chị Trâm chốt 17/08/2026 — giữ khớp app/api/roles/route.ts.
                    Level 1 KHÔNG có để chọn: phong/hạ Level 1 chỉ làm ở App Tổng (demo 28/09/2026). */}
                {roleGoc === 'BOOD' ? (
                  <option value="BOOD">{NHAN_LEVEL.BOOD}</option>
                ) : (['MANAGER', 'STAFF', 'VIEWER'] as const).map(v => (
                  <option key={v} value={v}>{NHAN_LEVEL[v]}</option>
                ))}
              </select>
              )}
              <p className="text-[9px] text-slate-400 mt-1 leading-tight">
                {isNew
                  ? 'Level lấy theo App Tổng. Đổi sau ở đây (Level 2–4) hoặc ở App Tổng.'
                  : (lyDoKhoa ? `🔒 ${lyDoKhoa}` : 'Lưu sẽ ghi thẳng về App Tổng.')}
              </p>
              {loiLevel && (
                <p className="text-[10px] text-brand-danger mt-1 leading-tight font-bold">{loiLevel}</p>
              )}
            </div>
          </div>

          {/* Quản lý phụ trách (đội ngũ) — chỉ Trưởng phòng (L1) gán, chỉ cho nhân viên Level 3.
              Quyết định Quản lý nào được XEM đội ngũ & KPI của nhân viên này (không đổi việc giao việc). */}
          {!isManager && role === 'STAFF' && (
            <div>
              <label className="block text-[9px] font-black uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">
                Quản lý phụ trách (đội ngũ)
              </label>
              <select
                value={quanLyPhuTrachId}
                onChange={(e) => setQuanLyPhuTrachId(e.target.value)}
                className="w-full px-2.5 py-1.5 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-700 dark:text-slate-200 bg-white dark:bg-dark-elevated focus:outline-none focus:ring-2 focus:ring-brand-accent"
              >
                <option value="">— Chưa gán (chỉ Trưởng phòng thấy) —</option>
                {managerOptions.map(m => {
                  const conLaQuanLy = (m.role || chucVuToRole(m.chucVu)) === 'MANAGER';
                  return (
                    <option key={m.id} value={m.id}>
                      {m.hoTen}{!conLaQuanLy ? ' — không còn là Quản lý, nên gán lại người khác' : ''}
                    </option>
                  );
                })}
              </select>
              <p className="text-[9px] text-slate-400 mt-1 leading-tight">
                Quản lý được gán sẽ thấy nhân viên này trong <b>Đội Ngũ &amp; KPI</b> và KPI Dashboard. Mỗi nhân viên chỉ thuộc 1 quản lý.
              </p>
            </div>
          )}

          {/* Chị Trâm chốt 17/08/2026: BỎ khối giải thích dài về phân quyền ở đây — nhìn rối và
              không chuyên nghiệp. Tên các Level ở ô chọn phía trên đã đủ nghĩa; chi tiết quyền hạn
              tra trong tài liệu bàn giao, không nhồi vào hộp thoại thêm nhân sự. */}

          {/* Actions */}
          <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100 dark:border-slate-800">
            <button 
              type="button"
              onClick={onClose}
              className="px-4 py-2 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-dark-elevated transition-colors"
            >
              Hủy bỏ
            </button>
            <button 
              type="submit"
              disabled={dangLuu}
              className="px-4 py-2 bg-brand-primary hover:bg-brand-primary-hover text-white rounded-lg text-xs font-black flex items-center gap-1.5 shadow-md transition-all cursor-pointer"
            >
              <Save className="w-3.5 h-3.5" />
              {dangLuu ? 'ĐANG LƯU…' : (isNew ? 'THÊM MỚI TÀI KHOẢN' : 'LƯU THAY ĐỔI')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
